language: node_js

node_js:
  - 0.10.43

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  # Todo: add these dependencies into package.json
  - npm install

script:
  - rm -rf .coverage/ && mkdir .coverage

    # Unit test using mocha
  - meteor npm run coverage-app-unit

    # Integration test using mocha
  - meteor npm run coverage-app-full

    # Save coverage now
  - cat .coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true # ignore coveralls error
  - cat .coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js || true # ignore codecov error
  - cat .coverage/lcov.info | ./node_modules/codecov.io/bin/codacy-coverage || true # ignore codacy error

    # Package test using mocha
  - meteor npm run coverage-packages-mocha

    # Package test using tinytest + coverage
    # is not supported anymore
    #- spacejam test-packages    --loglevel debug --coverage="out_lcovonly"
