language: node_js

node_js:
  - 0.10.43

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  - npm install -g coffee-script@1.8.0 https://github.com/serut/spacejam/tarball/master coveralls  codecov.io

script:
    # Spacejam is not supported by dispatch:mocha-phantomjs
    # and practicalmeteor:mocha-console-runner is outdated
    # moreover dispatch:mocha-phantomjs is not working on windows (TypeError: Cannot call method 'push' of undefined...)
    # ==> Coverage & CI is not working right now !

    # Update practicalmeteor:mocha-console-runner, looks good

    # Unit test using mocha
  - spacejam test            --loglevel debug --driver-package practicalmeteor:mocha-console-runner --coverage
    # Integration test using mocha
  - spacejam test --full-app --loglevel debug --driver-package practicalmeteor:mocha-console-runner --coverage
  - cat lcov.info | coveralls || true # ignore coveralls error
  - cat lcov.info | codecov || true # ignore codecov error
    # Package test using mocha
  - spacejam test-packages   --loglevel debug --driver-package practicalmeteor:mocha-console-runner --coverage
    # Package test using tinytest
  - spacejam test-packages   --loglevel debug --coverage
    # Package test using tinytest creates a coverage file with wrong path ?
  - cat lcov.info
