language: node_js

node_js:
  - 0.10.43

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  # Todo: add these dependencies into package.json
  - npm install -g https://github.com/serut/spacejam/tarball/windows-suppport-rc4 coveralls codecov.io

script:
    # Unit test using mocha
  - meteor npm run test-coverage-app-unit

    # Integration test using mocha
  - meteor npm run test-coverage-app-full

    # Save coverage now
  - cat lcov.info | coveralls || true # ignore coveralls error
  - cat lcov.info | codecov || true # ignore codecov error

    # Package test using mocha
  - meteor npm run test-coverage-packages-mocha

    # Package test using tinytest + coverage
    # is not supported anymore 
    #- spacejam test-packages    --loglevel debug --coverage="out_lcovonly"
